// Generated by CoffeeScript 1.3.3
(function() {

  jQuery(function($) {
    var init, notes, scrollable, shim;
    notes = $('#notes');
    init = function() {
      return scrollable();
    };
    scrollable = function() {
      notes.kinetic({
        triggerHardware: true
      });
      $('input, textarea, #note').focusout(function() {
        return notes.kinetic('attach');
      }).focusin(function() {
        return notes.kinetic('detach');
      });
      return shim();
    };
    shim = function() {
      $('#notes-by-group, #notes').wrapInner('<table cellspacing="30"><tr>');
      $('#notes-by-group .group:not(.all), .section').wrap('<td valign="top"></td>');
      $('#notes-by-group .group').each(function() {
        var group, size;
        group = $(this);
        notes = group.children('.group-of-notes').children('li');
        size = notes.size();
        if (group.hasClass('all')) {
          return group.css('width', ((size / 2) + 1) * 260);
        } else {
          return group.css('width', size > 3 ? 780 : size * 260);
        }
      });
      return $('#notes.kinetic-active').css({
        height: $(window).height() - $('#notes').offset().top
      });
    };
    return init();
  });

}).call(this);
